# Generated by Django 3.2.8 on 2021-11-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customerlenspackage',
            options={'verbose_name': 'Customer and their Lens Package', 'verbose_name_plural': 'Customers and their Lens Packages'},
        ),
        migrations.AlterModelOptions(
            name='lensaddons',
            options={'verbose_name': 'Lens Add-On', 'verbose_name_plural': 'Lens Add-Ons'},
        ),
        migrations.AlterModelOptions(
            name='lensmaterial',
            options={'verbose_name': 'Lens Material', 'verbose_name_plural': 'Lens Materials'},
        ),
        migrations.AlterModelOptions(
            name='lenspackage',
            options={'verbose_name': 'Lens Package', 'verbose_name_plural': 'Lens Packages'},
        ),
        migrations.AlterModelOptions(
            name='lenstype',
            options={'verbose_name': 'Lens Type', 'verbose_name_plural': 'Lens Types'},
        ),
    ]
