# Generated by Django 3.2.8 on 2021-11-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20211111_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenstype',
            name='static_img_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
