# Generated by Django 3.2.8 on 2021-11-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_lenstype_static_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensaddons',
            name='static_img_url',
            field=models.CharField(default='multiple_lenses.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='lensmaterial',
            name='static_img_url',
            field=models.CharField(default='multiple_lenses.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='lenspackage',
            name='static_img_url',
            field=models.CharField(default='multiple_lenses.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='lenstype',
            name='static_img_url',
            field=models.CharField(default='multiple_lenses.jpg', max_length=255),
        ),
    ]
