# Generated by Django 3.2.8 on 2021-11-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_auto_20211112_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensaddons',
            name='uploaded_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lensmaterial',
            name='uploaded_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lenspackage',
            name='uploaded_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lenstype',
            name='uploaded_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
