# Generated by Django 3.2.8 on 2021-11-17 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_auto_20211117_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenspackageitem',
            name='lens_add_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lensaddons'),
        ),
        migrations.AlterField(
            model_name='lenspackageitem',
            name='lens_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lensmaterial'),
        ),
        migrations.AlterField(
            model_name='lenspackageitem',
            name='lens_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lenspackage'),
        ),
        migrations.AlterField(
            model_name='lenspackageitem',
            name='lens_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lenstype'),
        ),
    ]
