# Generated by Django 3.2.8 on 2021-11-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0009_auto_20211117_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lenspackageitem',
            options={'verbose_name': 'Lens Packages and their items', 'verbose_name_plural': 'Lens Packages and their items'},
        ),
    ]
