# Generated by Django 3.2.8 on 2021-11-29 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0012_auto_20211119_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenspackageitem',
            name='lens_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lenspackage'),
            preserve_default=False,
        ),
    ]
