# Generated by Django 3.2.8 on 2021-12-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0017_lensdesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensDesignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Designs and their items',
                'verbose_name_plural': 'Lens Designs and their items',
            },
        ),
        migrations.RemoveConstraint(
            model_name='lenspackageitem',
            name='only_one_of_three_lens_categories_allowed',
        ),
        migrations.AddConstraint(
            model_name='lenspackageitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lens_type__isnull', False), ('lens_material__isnull', True), ('lens_add_on__isnull', True)), models.Q(('lens_type__isnull', True), ('lens_material__isnull', False), ('lens_add_on__isnull', True)), models.Q(('lens_type__isnull', True), ('lens_material__isnull', True), ('lens_add_on__isnull', False)), _connector='OR'), name='lens_package_only_one_of_three_lens_categories_allowed'),
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_add_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lensaddons'),
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.lensdesign'),
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lensmaterial'),
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lenstype'),
        ),
        migrations.AddConstraint(
            model_name='lensdesignitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('lens_type__isnull', False), ('lens_material__isnull', True), ('lens_add_on__isnull', True)), models.Q(('lens_type__isnull', True), ('lens_material__isnull', False), ('lens_add_on__isnull', True)), models.Q(('lens_type__isnull', True), ('lens_material__isnull', True), ('lens_add_on__isnull', False)), _connector='OR'), name='lens_design_only_one_of_three_lens_categories_allowed'),
        ),
    ]
