# Generated by Django 3.2.8 on 2021-12-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0018_auto_20211207_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensdesignitem',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
