# Generated by Django 3.2.8 on 2021-12-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0020_remove_lenspackageitem_lens_package_only_one_of_three_lens_categories_allowed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lensdesignitem',
            name='lens_design_only_one_of_three_lens_categories_allowed',
        ),
    ]
