# Generated by Django 3.2.8 on 2021-12-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0021_remove_lensdesignitem_lens_design_only_one_of_three_lens_categories_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensaddons',
            name='order_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lensdesign',
            name='order_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lensmaterial',
            name='order_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lenspackage',
            name='order_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lenstype',
            name='order_position',
            field=models.IntegerField(null=True),
        ),
    ]
