# Generated by Django 3.2.8 on 2021-12-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0022_auto_20211211_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenspackageitem',
            name='lens_add_on',
        ),
        migrations.RemoveField(
            model_name='lenspackageitem',
            name='lens_material',
        ),
        migrations.RemoveField(
            model_name='lenspackageitem',
            name='lens_package',
        ),
        migrations.RemoveField(
            model_name='lenspackageitem',
            name='lens_type',
        ),
        migrations.RenameField(
            model_name='lensaddons',
            old_name='default_price',
            new_name='retail_price',
        ),
        migrations.RenameField(
            model_name='lensmaterial',
            old_name='default_price',
            new_name='retail_price',
        ),
        migrations.RenameField(
            model_name='lenstype',
            old_name='default_price',
            new_name='retail_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lens_package',
        ),
        migrations.AddField(
            model_name='lensaddons',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_add_on_promo_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_add_on_retail_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_material_promo_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_material_retail_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_type_promo_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensdesignitem',
            name='lens_type_retail_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensmaterial',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lenstype',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lens_design_item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiosk.lensdesignitem'),
        ),
        migrations.DeleteModel(
            name='LensPackage',
        ),
        migrations.DeleteModel(
            name='LensPackageItem',
        ),
    ]
