# Generated by Django 3.2.8 on 2021-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0023_auto_20211212_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lensdesignitem',
            name='lens_add_on_promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lensdesignitem',
            name='lens_add_on_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lensdesignitem',
            name='lens_material_promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lensdesignitem',
            name='lens_material_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lensdesignitem',
            name='lens_type_promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lensdesignitem',
            name='lens_type_retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
