# Generated by Django 3.2.8 on 2022-01-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0027_auto_20220127_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensdesignitem',
            name='order_position',
            field=models.IntegerField(null=True),
        ),
    ]
